# This file was generated by GoReleaser. DO NOT EDIT.
cask "tent" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "b526c90a99f44a7e31370490bfa256eff790bfca7d0ce356326f31a435094883"
      url "https://github.com/ingvarch/tent/releases/download/v#{version}/tent_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d069f34cacc8a6374389ff16800cb76e4d96df081b0083a5b04c1dc7e4982930"
      url "https://github.com/ingvarch/tent/releases/download/v#{version}/tent_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "35e0b787a90da2ecd5931781a6172b655cadbd0e446318155f4755c4e6f72b9e"
      url "https://github.com/ingvarch/tent/releases/download/v#{version}/tent_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1fde7e9858b7315bffb3824514e38de408d25834453affec445e4e3ee412b47b"
      url "https://github.com/ingvarch/tent/releases/download/v#{version}/tent_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tent"
  desc "Provision and operate HashiCorp Nomad clusters on cloud providers"
  homepage "https://github.com/ingvarch/tent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tent"

  # No zap stanza required
end
