# This file was generated by GoReleaser. DO NOT EDIT.
cask "urga" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "dbde8b8ab519c18920cf4de3a099729f6c082fe424e72832ee694fbc681d0cfe"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5011562ad21f085a6f17e6037be69f763df6dc7d3150a339f68ba3670ade4e7b"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "76fba518218bcd151c3122026008e01f9f6f565939f0bad1cecf1fcb8a0c9760"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1d0762b0f1cd757a641700592bfb13e5de8086a378bd4b75b0b75ba5f5fa6d1"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_linux_amd64.tar.gz"
    end
  end

  name "urga"
  desc "Terminal UI for HashiCorp Nomad"
  homepage "https://github.com/ingvarch/urga"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urga"

  # No zap stanza required
end
