# This file was generated by GoReleaser. DO NOT EDIT.
cask "urga" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "0978609ea14ce070d2c10031b15d9867e55f326de5709abc40de2e3055ff2eb3"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cacc11c0c269524f148f58a23db4b193fd981ecdca86b657c2de4ccb614fa721"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8eceeccc4bd18b3a06f363d682d1535454aa0cd0055a982e545d194f430fb666"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f42d1906e19715cf49eed8d54568771fa1134cc1f2894f536cc1aa727a3d4b5b"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_linux_amd64.tar.gz"
    end
  end

  name "urga"
  desc "Terminal UI for HashiCorp Nomad"
  homepage "https://github.com/ingvarch/urga"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urga"

  # No zap stanza required
end
