# This file was generated by GoReleaser. DO NOT EDIT.
cask "urga" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "12dbbd497f29dba626758fe79bc55418d4789eed4a1b7c004cd5c340681cecc2"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "18c794b3f691157ccda209a209c1f4983b328a3d82cf47e1ddce197553ff031a"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d10dd5e7e2690e2a8508a45376f2a76556d58deafb407b94bc53658a675bba22"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "01ddab9bfbadb9bc4863ee8eb51e425cea9951ff8c4eab61c50c04a0b6015aeb"
      url "https://github.com/ingvarch/urga/releases/download/v#{version}/urga_#{version}_linux_amd64.tar.gz"
    end
  end

  name "urga"
  desc "Terminal UI for HashiCorp Nomad"
  homepage "https://github.com/ingvarch/urga"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urga"

  # No zap stanza required
end
